KDIR := $(HOME)/embedded_lab1/kernel/linux-5.15
ARCH := arm
CROSS_COMPILE := arm-linux-gnueabihf-

obj-m += lab2_driver.o
ccflags-y += -march=armv7-a
all:
	$(MAKE) -C $(KDIR) M=$(PWD) ARCH=$(ARCH) \
	CROSS_COMPILE=$(CROSS_COMPILE) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) ARCH=$(ARCH) \
	CROSS_COMPILE=$(CROSS_COMPILE) clean
