#!/bin/sh

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp
mount -t devtmpfs none /dev

echo "Loading LAB2 driver..."
insmod /lib/modules/5.15.0/lab2_driver.ko

if [ $? -eq 0 ]; then
    echo "LAB2 driver loaded"
    mknod /dev/lab2 c 240 0 2>/dev/null
else
    echo "ERROR: LAB2 driver failed"
fi

echo "Boot completed! Welcome to Embedded Linux Lab 2"
hostname embedded-lab


